CREATE TABLE MYUSER (
  ID NUMBER(10) NOT NULL,
  USERNAME VARCHAR (32) NOT NULL,
  NAME VARCHAR (64) NOT NULL,
  UNIQUE (USERNAME)
);

ALTER TABLE MYUSER ADD (
  CONSTRAINT MYUSER_PK     PRIMARY KEY (ID));

CREATE SEQUENCE MYUSER_SEQ START WITH 1;
